Week00/BOJ-1260/jiwon.java, Week00/BOJ-17478/jiwon.java, Week00/BOJ-7576/jiwon.java
[241025] java BOJ 1260, 17478, 7576 - 3문제
=> 파일럿 주 문제 제출

Week00/BOJ-1260/yeong.java
[241025] java BOJ 1260 / 3h / eunyeong - 1문제
=> Week 00: 문제 제출

Week01/PGS_이모티콘 할인행사/hoon.java
=> [24.10.28] PGS 이모티콘할인행사 - 1문제

Week01/BOJ_톱니바퀴/hoon.java
=> [2024-10-29] BOJ 톱니바퀴 - 1문제

Week02/BOJ_오르막 수/hoon.java
=> [24.11.01] BOJ 오르막 수 - 1문제

Week02/PGS_비밀지도/jun.java
https://school.programmers.co.kr/learn/courses/30/lessons/17681
#️⃣ PR 템플릿
=> [24.11.4] BOJ 비밀지도 - 김준영

Week02/BOJ_오르막 수/jun.java
https://www.acmicpc.net/problem/11057
#️⃣ PR 템플릿
=> [24.11.04] BOJ 오르막 수 - 김준영

Week02/BOJ_N과 M (1)/hoon.java, Week02/BOJ_N과 M (2)/hoon.java
=> [24.11.04] BOJ N과 M (1), (2) - 2문제

Week02/BOJ_N과 M (3)/hoon.java
=> [24.11.04] BOJ N과 M(3) - 1문제

Week02/BOJ_N-Queen/hoon.java
=> [24.11.05] BOJ N-Queen - 1문제

Week02/PGS_비밀지도/hoon.java
=> [24.11.01] PGS 비밀지도 - 1문제

Week02/BOJ_N-Queen/jun.java
https://www.acmicpc.net/problem/9663
#️⃣ PR 템플릿
=> [24.11.06] BOJ N-Queen - 1문제

Week02/BOJ_N과 M (1)/won.java, Week02/BOJ_N과 M (2)/won.java, Week02/BOJ_N과 M (3)/won.java, Week02/BOJ_오르막 수/won.java, Week02/PGS_비밀지도/won.java
#️⃣ PR 템플릿
[24.11.06] [JAVA] [BOJ] N과 M(1), N과 M(2), N과 M(3)/ S3(기본적인 백트래킹 문제 -> 외워서 다른 백트래킹 문제 활용)
[24.11.06] [JAVA] [BOJ] 오르막 수/ S1 (표 그렸던 것과 규칙 찾았던 것 다시 복습)
[24.11.06] [JAVA] [PGS] 비밀지도/ Lv1(다른 사람들 푼 방법 참고해보기 <- 풀이방법이 다양할 것 같음)
=> [24.11.06] {JAVA} {필수 문제 5개} - {구지원}

Week02/PGS_하노이의 탑/won.java
=> [24.11.07] [JAVA] 하노이의 탑

Week03/BOJ_2 x n 타일링/hoon.cpp, Week03/BOJ_2048 (Easy)/hoon.cpp, Week03/BOJ_가장 긴 감소하는 부분 수열/hoon.cpp, Week03/BOJ_녹색 옷을 입은 애가 젤다지/hoon.cpp, Week03/PGS_도넛과 막대 그래프/hoon.cpp
=> [24.11.09] BOJ 2xn 타일링 - 1문제

Week03/BOJ_2 x n 타일링/hoon.java
=> [24.11.09] BOJ 2 x n 타일링 - 1문제, 자바 풀이

Week02/BOJ_N-Queen/Bae.java, Week02/PGS_하노이의 탑/Bae.java
#️⃣ PR 템플릿
[24.11.11] 
[[PGS] 하노이의 탑] - DP와 관련하여 복습이 필요하다.
=> Week02 - 추가문제 - 하노이의 탑, N-Queen

Week03/BOJ_가장 긴 감소하는 부분 수열/jun.java, Week03/BOJ_녹색 옷을 입은 애가 젤다지/jun.java, Week03/PGS_도넛과 막대 그래프/jun.java
=> [24.11.13] 3주차 필수문제 3문제 - 도넛, 수열, 젤다

Week03/PGS_도넛과 막대 그래프/hoon.java
=> [24.11.13] PGS 도넛과 막대 그래프 - 1문제

Week03/BOJ_가장 긴 감소하는 부분 수열/yeong.java, Week03/BOJ_녹색 옷을 입은 애가 젤다지/yeong.java, Week03/PGS_도넛과 막대 그래프/yeong.java
#️⃣ PR 템플릿
[BOJ] 4485번 녹색 옷 입은 애가 젤다지 ?
[PGS] 도넛과 막대 그래프
두 문제 혼자 해결하지 못한 문제이므로 복습이 필요합니다
=> Week 03: 문제 제출 / 장은영

Week03/.idea/.gitignore, Week03/.idea/misc.xml, Week03/.idea/modules.xml, Week03/.idea/vcs.xml, Week03/BOJ_가장 긴 감소하는 부분 수열/won.py, Week03/BOJ_녹색 옷을 입은 애가 젤다지/won.py, Week03/PGS_도넛과 막대 그래프/won.py, Week03/Week03.iml
=> [24.11.15] 3주차 필수문제 - 젤다, 노넛, 감소하는 수열

Week03/BOJ_2 x n 타일링/jun.java
https://www.acmicpc.net/problem/11726
#️⃣ PR 템플릿
=> [24.11.15] 추가문제 1문제 - 타일링

Week04/.idea/.gitignore, Week04/.idea/misc.xml, Week04/.idea/modules.xml, Week04/.idea/vcs.xml, Week04/Week03.iml
=> Chore: 폴더 생성

Week04/BOJ_가장 긴 감소하는 부분 수열2/jun.java, Week04/BOJ_경사로/jun.java, Week04/PGS_성격유형검사하기/jun.java
=> [24.11.20] 4주차 필수문제 3문제 - 경사로, 수열, 성격유형

Week04/BOJ_가장 긴 감소하는 부분 수열2/won.py, Week04/PGS_성격유형검사하기/won.py
=> [24.11.20] 4주차 필수문제 2문제 - 성격유형, 부분 수열

.idea/misc.xml
=> [24.11.21] BOJ  - 필수 문제 3문제, 특별 문제 1문제

Week04/BOJ_2048 (Easy)/jun.java
https://www.acmicpc.net/problem/12100
#️⃣ PR 템플릿
=> [24.11.21] 선택 문제 1문제 - 2048

Week04/BOJ_가장 긴 감소하는 부분 수열2/hoon.java, Week04/BOJ_가장 긴 증가하는 부분 수열5/hoon.java, Week04/BOJ_경사로/hoon.java, Week04/PGS_성격유형검사하기/hoon.java
=> [24.11.22] BOJ 필수문제 - 3문제

Week05/BOJ_LCS/won.java, Week05/BOJ_최대 페이지 수/won.java, Week05/BOJ_최소 스패닝 트리/won.java
=> [24.11.28] 5주차 필수문제 - 3문제/ 지원

Week05/BOJ_LCS/yeong.java, Week05/BOJ_최대 페이지 수/yeong.java, Week05/BOJ_최소 스패닝 트리/yeong.java
#️⃣ PR 템플릿
백준 1197번 최소 스패닝 트리 - 이해 부족으로 복습 필요
백준 9251번 LCS - 이해 부족으로 복습 필요
=> [24.11.28] 필수문제 3문제 - 장은영

Week05/BOJ_LCS/jun.java, Week05/BOJ_최대 페이지 수/jun.java, Week05/BOJ_최소 스패닝 트리/jun.java
=> [24.11.28] 필수 문제 3문제 - 준영

Week06/.idea/.gitignore, Week06/.idea/misc.xml, Week06/.idea/modules.xml, Week06/.idea/vcs.xml, Week06/Week03.iml
=> rename: 6주차 폴더 생성

Week06/PGS_다리를 지나는 트럭/Bae.java, Week06/PGS_블록 이동하기/Bae.java, Week06/PGS_양과 늑대/Bae.java
#️⃣ PR 템플릿
[PGS] 블록 이동하기 / L3 / 4h / 배재유
[PGS] 양과 늑대/ L3 / 3.5h / 배재유
구현 문제에서 케이스에 따른 경우를 좀 더 신경써보자
=> [24.12.06] 필수문제 3문제 - 배재유

Week06/PGS_다리를 지나는 트럭/yeong.java, Week06/PGS_블록 이동하기/yeong.java, Week06/PGS_양과 늑대/yeong.java
=> [24.12.05] 필수문제 3문제 - 은영

Week06/PGS_다리를 지나는 트럭/won.java
=> [24.12.04] 6주차 필수문제(다리를 지나는 트럭) -1문제

Week07/BOJ_가운데를 말해요/jun.java, Week07/BOJ_노드사이의 거리/jun.java, Week07/PGS_더 맵게/jun.java
#️⃣ PR 템플릿
[24.12.13] BOJ 노드사이의 거리 - 그냥 단순한 DFS를 돌렸으면 시간 초과가 나는지 코드 리뷰 필요
[24.12.13] BOJ 가운데를 말해요 - min,max heap을 쓰는 풀이 외의 다른 풀이 참고
=> [24.12.13] 필수 문제 3문제 - 김준영

Week07/BOJ_가운데를 말해요/Bae.java, Week07/BOJ_노드사이의 거리/Bae.java, Week07/PGS_더 맵게/Bae.java
#️⃣ PR 템플릿
[필수문제 3문제] - 힙에 대해 몇 번 보더라도 아직 뭔지 잘 모르겠다. 자료 구조 다시 한번 확인
=> [24.12.12] 필수문제 3문제 - 배재유

Week07/BOJ_가운데를 말해요/won.java, Week07/PGS_더 맵게/won.java
=> [24.12.13] 7주차 필수문제 - 2문제

Week08/BOJ_마법사 상어와 토네이도/jun.java, Week08/BOJ_여행 가자/jun.java, Week08/PGS_삼각 달팽이/jun.java, Week08/PGS_숫자 카드 나누기/jun.java
#️⃣ PR 템플릿
[PGS] 숫자 카드 나누기 - 최대공약수 함수를 만들어서 풀이 참고
[BOJ] 마법사 상어와 토네이도 - 구현에 있어서 더 효율적인 풀이 참고
[BOJ] 여행 가자 - 아마 다들 비슷하게 풀었을 것이라 예상
[PGS] 삼각 달팽이 - 직각 삼각형으로만 생각하면 비슷한 풀이 예상
=> [24.12.19] 8주차 필수문제 3문제 , 추가문제 1문제 - 김준영

Week08/BOJ_마법사 상어와 토네이도/won.java, Week08/BOJ_여행 가자/won.java, Week08/PGS_숫자 카드 나누기/won.java
=> [24.12.20] 8주차 필수문제 3문제 - 구지원

Week08/BOJ_마법사 상어와 토네이도/yeong.java, Week08/BOJ_여행 가자/yeong.java, Week08/PGS_숫자 카드 나누기/yeong.java
#️⃣ PR 템플릿
숫자카드 나누기 - 유클리드 호제법 다시 복습할 필요가 있습니다
마법사 상어와 토네이도 - 문제 이해도 어렵고 구현도 연습할 필요가 있습니다
여행가자 - 문제 이해와 풀이를 떠올리는것부터 어려웠던 문제여서 복습할 필요가 있습니다
=> [24.12.20] 8주차 필수문제 3문제 - 장은영

Week08/BOJ_마법사 상어와 토네이도/Bae.java, Week08/BOJ_여행 가자/Bae.java, Week08/PGS_숫자 카드 나누기/Bae.java
#️⃣ PR 템플릿
[[BOJ] 마법사 상어와 토네이도 / G3 / 4h / 배재유]
구현 문제에 대해 좀 더 확인해야한다
=> [24.12.20] 필수문제 3문제 - 배재유

Week09/BOJ_달팽이/yeong.java, Week09/BOJ_달팽이2/yeong.java, Week09/BOJ_달팽이3/yeong.java, Week09/BOJ_달팽이는 올라가고 싶다/yeong.java
#️⃣ PR 템플릿
BOJ 달팽이3 - 문제를 풀이하는 아이디어 자체를 떠올리기 힘들었으므로 복습 필요
BOJ 달팽이 - 복습 필요
=> [24.12.27] 9주차 필수문제 4문제 - 장은영

Week10/BOJ_미로 탐색/hoon.java, Week10/BOJ_에디터/hoon.java, Week10/BOJ_역사/hoon.java
[25.01.01] BOJ 미로 탐색 - 1문제
[25.01.02] BOJ 에디터 - 1문제
=> [25.01.02] BOJ 필수 문제 - 3문제

Week10/BOJ_미로 탐색/Bae.java, Week10/BOJ_에디터/Bae.java, Week10/BOJ_역사/Bae.java
#️⃣ PR 템플릿
[[BOJ] 역사 / G3 / 70m / 배재유]
플로이드 워셜에서 중간 지점에 대한 파악이 중요하다.
=> [25.01.02] 필수문제 3문제 - 배재유

Week10/BOJ_미로 탐색/yeong.java, Week10/BOJ_에디터/yeong.java, Week10/BOJ_역사/yeong.java
#️⃣ PR 템플릿
BOJ 역사 - 플로이드워셜에 대해 복습 필요
=> [25.01.02] 10주차 필수문제 3문제 - 장은영

Week10/BOJ_역사/yeong.java, Week11/BOJ_A와 B/yeong.java, Week11/BOJ_감시/yeong.java, Week11/BOJ_꿀 아르바이트/yeong.java
=> [25.01.09] 11주차 필수문제 3문제 - 장은영

Week11/BOJ_A와 B/Bae.java, Week11/BOJ_감시/Bae.java, Week11/BOJ_꿀 아르바이트/Bae.java
#️⃣ PR 템플릿
[[BOJ] 감시 / G3 / 3h / 배재유]
반복문을 최대한 간단하게 줄이도록 노력하자
=> [25.01.09] 필수문제 3문제 - 배재유

Week12/BOJ_A와 B 2/Bae.java, Week12/BOJ_숨바꼭질/Bae.java, Week12/PGS_표 편집/Bae.java
=> [25.01.16] 필수문제 3문제 - 배재유

Week12/BOJ_A와 B 2/won.java, Week12/BOJ_구간 합 구하기 4/won.java, Week12/BOJ_숨바꼭질/won.java, Week12/PGS_표 편집/won.java
=> [25.01.19] 12 주차 필수문제 3문제, 선택문제 1문제 - 구지원

Week12/BOJ_숨바꼭질/yeong.java, Week13/BOJ_조약돌 꺼내기/yeong.java, Week13/BOJ_행렬 곱셈 순서/yeong.java, Week13/PGS_산 모양 타일링/yeong.java
=> [25.01.23] 13주차 필수 문제 3문제 - 장은영

Week13/BOJ_조약돌 꺼내기/won.java, Week13/BOJ_행렬 곱셈 순서/won.java, Week13/PGS_산 모양 타일링/won.java
…/ Lv 3/ 180m/ 구지원
[BOJ] 조약돌 꺼내기/ S3/ 1H/ 구지원
[BOJ] 행렬 곱셈 순서/ G3/ 2H/ 구지원
[PGS] 산 모양 타일링/ Lv 3/ 180m/ 구지원
#️⃣ PR 템플릿
=> [25.01.24] 13주차 필수문제 3문제 - 구지원

Week13/ [BOJ] 행렬 곱셈 순서/Bae.java, Week13/ [PGS] 산 모양 타일링/Bae.java, Week13/[BOJ] 조약돌 꺼내기/Bae.java
#️⃣ PR 템플릿
[[PGS] 산 모양 타일링 / Lv 3 / 2h / 배재유]
[[BOJ] 행렬 곱셈 순서/ G3 / 150m / 배재유]
=> [25.01.24] 필수문제 3문제 - 배재유

Week14/BOJ_DNA 비밀번호/won.java, Week14/BOJ_텀 프로젝트/won.java, Week14/PGS_n+1카드게임/won.java
[BOJ] DNA 비밀번호/ S2/ 40min/ 지원
[PGS] n+1카드게임/ lv 3/ 3h/ 지원
#️⃣ PR 템플릿
=> [25.02.07] 14주차 필수문제 - 3문제

Week15/BOJ_동전 1/hoon.java, Week15/BOJ_등굣길/hoon.java, Week15/PGS_경주로 건설/hoon.java, Week15/PGS_문자열 압축/hoon.java
=> [25.02.13] 필수문제 - 3문제, 선택문제 - 등굣길

Week15/BOJ_동전1/Main.java, Week15/PGS_경주로건설/Solution.java, Week15/PGS_문자열압축/Solution.java
… LV 2/ 2h/ 구지원
[BOJ] 동전 1/ G4/ 2h/ 구지원
[PGS] 경주로 건설/ LV 3/ 2.5h/ 구지원
[PGS] 문자열 압축/ LV 2/ 2h/ 구지원
#️⃣ PR 템플릿
=> [25.02.14] 15주차 필수문제 - 3문제

Week15/BOJ_동전 1/yune.swift, Week15/PGS_경주로 건설/yune.swift, Week15/PGS_문자열 압축/yune.swift
=> [25.02.13] 필수문제 - 3문제

.idea/Algorithm_Study.iml, .idea/codeStyles/codeStyleConfig.xml, .idea/uiDesigner.xml, Week16/BOJ_동전 2/hoon.java, Week16/PGS_카드 짝 맞추기/hoon.java, Week16/PGS_코딩 테스트 공부/hoon.java
=> [25.02.20] 필수 문제 - 3문제

Week16/.idea/.gitignore, Week16/.idea/misc.xml, Week16/.idea/modules.xml, Week16/.idea/vcs.xml, Week16/BOJ_동전2/Main.java, Week16/PGS_카드짝맞추기/Solution.java, Week16/PGS_코딩테스트공부/Solution.java, Week16/Week16.iml
=> [25.02.23] 16주차 필수문제 3문제 - 구지원

Week17/.idea/misc.xml, Week17/.idea/modules.xml, Week17/.idea/vcs.xml, Week17/.idea/workspace.xml, Week17/BOJ_도시분할계획/Main.java, Week17/BOJ_말이되고픈원숭이/Main.java, Week17/PGS_[3차] 자동완성/Solution.java, Week17/Week17.iml
…고픈 원숭이/ G3/ 90m/ 구지원
#️⃣ PR 템플릿
=> [25.02.28]17주차 필수문제 3문제 - 구지원

Week18/BOJ_RGB거리 2/yune.swift, Week18/BOJ_개미굴/yune.swift, Week18/BOJ_디스크 트리/yune.swift, Week18/BOJ_맥주 마시면서 걸어가기/yune.swift, Week18/BOJ_부재중 전화/yune.swift, Week18/BOJ_전력난/yune.swift
=> [25.03.07] 필수 3문제 + 선택 3문제

.idea/misc.xml, Week11/.idea/.gitignore, Week11/.idea/misc.xml, Week11/.idea/modules.xml, Week11/.idea/vcs.xml, Week11/Week11.iml, Week13/.idea/misc.xml, Week13/.idea/modules.xml, Week13/.idea/vcs.xml, Week13/.idea/workspace.xml, Week13/Week13.iml, Week15/.idea/misc.xml, Week15/.idea/modules.xml, Week15/.idea/vcs.xml, Week15/.idea/workspace.xml, Week15/Week15.iml, Week18/.idea/.gitignore, Week18/.idea/misc.xml, Week18/.idea/modules.xml, Week18/.idea/vcs.xml, Week18/BOJ_개미굴/won.java, Week18/BOJ_디스크트리/won.java, Week18/BOJ_전력난/won.java, Week18/Week18.iml
깃허브 에러가 나서 로컬 파일을 다 업로드 했더니,,, 너무 많은 파일이 업로드 되었습니다 ㅠㅠ
=> [25.03.07] 18주차 필수문제 3문제 -구지원

Week20/BOJ_가장가까운공통조상/Main.java, Week20/BOJ_주사위굴리기/Main.java, Week20/PGS_완전범죄/Solution.java
=> 20주차 필수문제 3문제 - 구지원

Week21/LTC_Find_All_Possible_Recipes_from_Given_Supplies/won.java, Week21/PGS_공_이동_시뮬레이션/won.java
=> [25.03.28] 필수문제 2문제

Week27/BOJ_두_용액/hoon.java, Week27/BOJ_망가진_키보드/hoon.java, Week27/BOJ_스터디_시간_정하기_1/hoon.java, Week27/BOJ_좋은_친구/hoon.java
=> [25.05.08] 4문제

Week35/[BOJ] Gaaaaaaaaaarden/hoon.java, Week35/[BOJ] N-Queen/hoon.java, Week35/[BOJ] N과 M (11)/hoon.java, Week35/[BOJ] N과 M (12)/hoon.java, Week35/[BOJ] 계란으로 계란치기/hoon.java, Week35/[BOJ] 로또/hoon.java, Week35/[BOJ] 비숍/hoon.java, Week35/[BOJ] 소문난 칠공주/hoon.java, Week35/[BOJ] 암호 만들기/hoon.java
=> [25.07.06] 필수문제 9문제
